{
  "$schema": "node_modules/wrangler/config-schema.json",
  "name": "personal-dashboard-worker",
  "main": "src/worker.ts",
  "compatibility_date": "2025-03-30",
  "account_id": "7870663c256e665e939a8d93758c54e3",
  "route": "personal.tivnan.net/api/todoist/*",
  "compatibility_flags": ["nodejs_compat"]
}
